#!/usr/local/bin/bash

source "${__shdocker_script_dir}/deps/shlogging/shlogging"

function _docker_login () {
  _assert "'${REGISTRY_USERNAME}' != ''" "Require 'REGISTRY_USERNAME'"
  _assert "'${REGISTRY_PASSWORD}' != ''" "Require 'REGISTRY_PASSWORD'"

  _info "Login to docker registry ${REGISTRY_HOST}"
  if [[ "${REGISTRY_USERNAME}" != "" ]] && [[ "${REGISTRY_PASSWORD}" != "" ]]; then
    for try in {1..10} ; do
      _info "Trying to login to ${REGISTRY_HOST} as user ${REGISTRY_USERNAME}"
      local RESULT=$(docker login -u "${REGISTRY_USERNAME}" -p "${REGISTRY_PASSWORD}" "${REGISTRY_HOST}")

      if [[ "$(echo ${RESULT}|grep 'Succeeded')" != "" ]]; then
        _info "Login to ${REGISTRY_HOST} as user ${REGISTRY_USERNAME} succeed"
        break
      fi
    done
  fi
}